blank_issues_enabled: true
contact_links:
  - name: Discord Community
    url: https://discord.com/channels/1022871757289422898/1458840574076387448
    about: Join our Discord channel for discussions and support (MANDATORY for all contributors)
  - name: AOSSIE Website
    url: https://aossie.org/
    about: Learn more about AOSSIE and our projects
